INSERT INTO [Quiz] ([Name], [PotatoTeacherId], [PathFile])
VALUES
('Advanced SQL Concepts', 1, '/quizzes/Advanced_SQL_Concepts.json'),
('Database Optimization Techniques', 2, '/quizzes/Database_Optimization_Techniques.json'),
('Data Modeling for Beginners', 3, '/quizzes/Data_Modeling_for_Beginners.json'),
('Query Performance Tuning', 4, '/quizzes/Query_Performance_Tuning.json'),
('Working with JSON in SQL Server', 5, '/quizzes/Working_with_JSON_in_SQL_Server.json'),
('Introduction to Relational Databases', 6, '/quizzes/Introduction_to_Relational_Databases.json'),
('SQL Query Writing Basics', 7, '/quizzes/SQL_Query_Writing_Basics.json'),
('Understanding Indexes and Joins', 8, '/quizzes/Understanding_Indexes_and_Joins.json'),
('Mastering Subqueries and CTEs', 9, '/quizzes/Mastering_Subqueries_and_CTEs.json'),
('T-SQL Functions Explained', 10, '/quizzes/T-SQL_Functions_Explained.json'),
('Relational Database Design', 11, '/quizzes/Relational_Database_Design.json'),
('Handling NULL Values in SQL', 12, '/quizzes/Handling_NULL_Values_in_SQL.json'),
('Advanced JOIN Techniques', 13, '/quizzes/Advanced_JOINS_Techniques.json'),
('Database Security Best Practices', 14, '/quizzes/Database_Security_Best_Practices.json'),
('Backup and Restore Strategies', 15, '/quizzes/Backup_and_Restore_Strategies.json'),
('Replication and High Availability', 16, '/quizzes/Replication_and_High_Availability.json'),
('Data Warehousing Fundamentals', 17, '/quizzes/Data_Warehousing_Fundamentals.json'),
('Stored Procedures and Triggers', 18, '/quizzes/Stored_Procedures_and_Triggers.json'),
('Using Views for Data Abstraction', 19, '/quizzes/Using_Views_for_Data_Abstraction.json'),
('Query Optimization Techniques', 20, '/quizzes/Query_Optimization_Techniques.json'),
('Understanding Execution Plans', 21, '/quizzes/Understanding_Execution_Plans.json'),
('Working with Temp Tables and Table Variables', 22, '/quizzes/Working_with_Temp_Tables_and_Table_Variables.json'),
('SQL Server Architecture Overview', 23, '/quizzes/SQL_Server_Architecture_Overview.json'),
('Basic SELECT and WHERE Clauses', 24, '/quizzes/Basic_SELECT_and_WHERE_Clauses.json'),
('GROUP BY and HAVING Clauses', 25, '/quizzes/GROUP_BY_and_HAVING_Clauses.json'),
('Aggregate Functions in SQL', 26, '/quizzes/Aggregate_Functions_in_SQL.json'),
('Filtering Results with HAVING', 27, '/quizzes/Filtering_Results_with_HAVING.json'),
('Subqueries in Practice', 28, '/quizzes/Subqueries_in_Practice.json'),
('Common Table Expressions (CTEs)', 29, '/quizzes/Common_Table_Expressions_CTEs.json'),
('Window Functions for Analytics', 30, '/quizzes/Window_Functions_for_Analytics.json'),
('Pivot and Unpivot Operations', 31, '/quizzes/Pivot_and_Unpivot_Operations.json'),
('Error Handling in T-SQL', 32, '/quizzes/Error_Handling_in_T_SQL.json'),
('Transactions and ACID Properties', 33, '/quizzes/Transactions_and_ACID_Properties.json'),
('Deadlocks and Locking in SQL Server', 34, '/quizzes/Deadlocks_and_Locking_in_SQL_Server.json'),
('Index Management and Maintenance', 35, '/quizzes/Index_Management_and_Maintenance.json'),
('Data Migration Strategies', 36, '/quizzes/Data_Migration_Strategies.json'),
('ETL Process Overview', 37, '/quizzes/ETL_Process_Overview.json'),
('SQL Server Security Concepts', 38, '/quizzes/SQL_Server_Security_Concepts.json'),
('Understanding Query Plans', 39, '/quizzes/Understanding_Query_Plans.json'),
('Optimizing Slow Queries', 40, '/quizzes/Optimizing_Slow_Queries.json'),
('Working with XML Data', 41, '/quizzes/Working_with_XML_Data.json'),
('Introduction to NoSQL Databases', 42, '/quizzes/Introduction_to_NoSQL_Databases.json'),
('Cloud Database Solutions', 43, '/quizzes/Cloud_Database_Solutions.json'),
('Database Normalization Techniques', 44, '/quizzes/Database_Normalization_Techniques.json'),
('Advanced Filtering with WHERE', 45, '/quizzes/Advanced_Filtering_with_WHERE.json'),
('SQL Server Performance Monitoring', 46, '/quizzes/SQL_Server_Performance_Monitoring.json'),
('Understanding Deadlocks', 47, '/quizzes/Understanding_Deadlocks.json'),
('Backup and Recovery Planning', 48, '/quizzes/Backup_and_Recovery_Planning.json'),
('Data Integrity Constraints', 49, '/quizzes/Data_Integrity_Constraints.json'),
('Mastering the CASE Statement', 50, '/quizzes/Mastering_the_CASE_Statement.json'),
('Using UNION and INTERSECT', 51, '/quizzes/Using_UNION_and_INTERSECT.json');
